# Linear Algebra in Python

In [1]:
import numpy as np

In [2]:
# coefficeient matrix A 

A = np.array([[2,3], [5,7]])     # 2x2 matrix

A

array([[2, 3],
       [5, 7]])

In [3]:
# constant matrix B 

B = np.array([8,20])
B

array([ 8, 20])

2x + 3y = 8

5x + 4y = 20 


In [6]:
# solve for x 

X = np.linalg.solve(A,B) 

X

array([4., 0.])

# Solving Complex Equations

### letax language


\[
\begin{align*}
(1+2i)x +( 2-i)y &=4+i \\
(3-i)x + 4y &= 3 +4i
\end{align*}
\]

In [11]:
# Coefficients matrix A with complex numbers

A_complex = np.array([[1+2j, 2-1j], [3-1j, 4]])

A_complex

array([[1.+2.j, 2.-1.j],
       [3.-1.j, 4.+0.j]])

In [12]:
# Constants matrix B with complex numbers

B_complex = np.array([4+1j, 3+4j])
B_complex

array([4.+1.j, 3.+4.j])

In [10]:

# solving for X in the complex case 

X_complex = np.linalg.solve(A_complex, B_complex)
X_complex

array([-0.11176471-0.45294118j,  0.94705882+1.31176471j])

# vectors in Python

In [13]:
import numpy as np
import matplotlib.pyplot as plt

In [14]:
# create a vector

v = np.array([2,3])
v

array([2, 3])

In [ ]:
# plot the vector v

