# NumPy in Detail

In [1]:
# pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
# Import numpy

import numpy as np

### What is an Array?

An array is a collection of items stored in contiguous memory locations. It is a simple data structure that enables users to store multiple values in a single variable. Each element of an array has a specific index or position that corresponds to its location in memory.

Arrays can store elements of the same data type. In many programming languages, the type of the elements in an array is determined when the array is declared.

## create numpy array

In [3]:
arr =np.arange(8)
print(arr)

[0 1 2 3 4 5 6 7]


## Convert one Dim array to two Dim. array

In [4]:
arr2 = arr[np.newaxis, :]
print(arr2)

[[0 1 2 3 4 5 6 7]]


In [7]:
arr3 = arr[:,np.newaxis]
print(arr3)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


## 3D Array

In [9]:
a3 = arr2[np.newaxis, :]
print(a3)

[[[0 1 2 3 4 5 6 7]]]


In [13]:
a4 = arr2[:, np.newaxis]
print(a4)

[[[0 1 2 3 4 5 6 7]]]


## check shape

In [5]:
arr.shape

(8,)

In [6]:
arr2.shape

(1, 8)

In [8]:
arr3.shape

(8, 1)

In [14]:
a3.shape

(1, 1, 8)

In [15]:
a4.shape

(1, 1, 8)

# Creating Arrays with NumPy

In [20]:
a = np.array([1,3,4,8,3,0,83,8])
b= np.array([(1,3,8,88,28,9), (3,1,88,8,9,23)])
print(a)
print('******************')
print(b)

[ 1  3  4  8  3  0 83  8]
******************
[[ 1  3  8 88 28  9]
 [ 3  1 88  8  9 23]]


In [17]:
a.shape

(8,)

In [18]:
b.shape

(2, 6)

## Initialize Arrays

In [21]:
zeros = np.zeros((3,4))  # (Rows , Columns)

zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
zeros = np.zeros((8,12))
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
ones = np.ones((3,6))
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
full = np.full((3,8), 9)

full

array([[9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9]])

## Matrix

Identity matrix

In [25]:
identity = np.eye(5)

identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Check Data Type

In [26]:
arr.dtype

dtype('int32')

In [27]:
arr2.dtype

dtype('int32')

In [28]:
zeros.dtype

dtype('float64')

In [29]:
ones.dtype

dtype('float64')

In [30]:
b.dtype

dtype('int32')

In [31]:
full.dtype

dtype('int32')

# Check type of Data

In [32]:
type(arr)

numpy.ndarray

In [33]:
type(arr2)

numpy.ndarray

In [34]:
type(zeros)

numpy.ndarray

In [35]:
type(ones)

numpy.ndarray

# Attributes of Array

### Shape of array

In [36]:
arr.shape

(8,)

### length of array

In [37]:
len(arr)

8

### Dimension of array

In [38]:
a.ndim

1

In [40]:
arr2.ndim

2

In [41]:
zeros.ndim

2

In [42]:
full.ndim

2

### size of array

In [43]:
arr.size

8

In [44]:
a.size

8

In [45]:
full.size

24

In [46]:
zeros.size

96

## Basic Operations

Addition

In [47]:
print(arr)

[0 1 2 3 4 5 6 7]


In [48]:
print(arr2)

[[0 1 2 3 4 5 6 7]]


In [49]:
print(zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [50]:
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [51]:
print(full)

[[9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]]


In [52]:
add= arr-arr2
print(add)

[[0 0 0 0 0 0 0 0]]


In [53]:
add2 = arr+arr
print(add2)

[ 0  2  4  6  8 10 12 14]


In [56]:
h1 = np.add(arr, arr2)
h1

array([[ 0,  2,  4,  6,  8, 10, 12, 14]])

Subtraction

In [58]:
sub = arr-arr2
sub

array([[0, 0, 0, 0, 0, 0, 0, 0]])

Multiplication

In [59]:
mul = arr*arr2
mul

array([[ 0,  1,  4,  9, 16, 25, 36, 49]])

Division

In [61]:
div = arr/arr2
div

C:\Users\Saurabh Kumar\AppData\Local\Temp\ipykernel_19656\2958894824.py:1: RuntimeWarning: invalid value encountered in divide
  div = arr/arr2


array([[nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

Square

In [62]:
sqr = np.square(arr2)
sqr

array([[ 0,  1,  4,  9, 16, 25, 36, 49]])

Squeeze

In [63]:
squ = np.squeeze(arr)
squ

array([0, 1, 2, 3, 4, 5, 6, 7])

sqrt

In [64]:
squt = np.sqrt(arr2)
squt

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131]])